FROM debian
COPY vimexx-dns /root
COPY docker/start.sh /root
RUN set -x ; \
    apt-get update \
    && apt-get -y install libjson-perl libappconfig-std-perl liblwp-protocol-https-perl
ENTRYPOINT ["/root/start.sh"]
